<?php
/**
* Advanced Config For FormBuilder Module
*/
/**
* This is an advanced configuration file
* Don't mess with this unless you know what you are doing
* or explicitly told to do so by a developer
*/

/**
* These preferences were removed from settings since 0.8.1
* Scheduled for removal unless proven to be necessary
*/

/**
* Enable Fast Field Add Pulldown
* 
* @var bool
*/
$fbcfg['show_version'] 		= FALSE;

/**
* Show Form Builder Version
* 
* @var bool
*/
$fbcfg['enable_fastadd'] 	= TRUE;

/**
* Show Field IDs
* 
* @var bool
*/
$fbcfg['show_fieldids'] 	= TRUE;

/**
* Show Field IDs
* 
* @var bool
*/
$fbcfg['show_fieldaliases']   = TRUE;

/**
* Show Field IDs
* 
* @var bool
*/
$fbcfg['enable_antispam'] 	= FALSE;
?>
